services:

  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: info-auth-api

    ports:
      - "${PORT}:3000"

    env_file:
      - .env

    depends_on:
      - postgres

    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: postgres-auth
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_EXPOSED_PORT:-5450}:5432" # Expõe a 5450 no Host para a 5432 do Container

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
